name: Miri

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  miri:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Miri test uacryptex-core
        run: cargo miri test -p uacryptex-core --lib
